/**
 * Default content keys per section.
 * Used by the admin CMS to seed missing content automatically.
 */
export const SECTION_DEFAULTS: Record<string, Record<string, string>> = {
  // ── Global (always loaded alongside any section) ──
  global: {
    back: "Voltar",
    save_btn: "Salvar",
    cancel: "Cancelar",
    loading: "Carregando...",
    theme_light: "Claro",
    theme_dark: "Escuro",
    theme_auto: "Auto",
    save_error: "Erro ao salvar",
    save_success: "Salvo com sucesso",
    confirm: "Confirmar",
    search_placeholder: "Buscar...",
    empty: "Nenhum resultado encontrado",
    error_generic: "Algo deu errado",
  },

  // ── Home public ──
  hero: {
    hero_title: "Compre online. Doe automaticamente.",
    hero_subtitle: "Seu cashback vira doação para ONGs. Sem custo extra.",
    hero_cta: "Começar a doar",
    hero_cta_secondary: "Como funciona?",
    hero_badge: "100% gratuito",
    hero_stats: "+R$ 50.000 doados",
  },
  how_it_works: {
    how_title: "Como funciona?",
    how_subtitle: "3 passos simples para transformar suas compras em doações",
    how_step1_title: "Escolha uma ONG",
    how_step1_desc: "Selecione a causa que mais te inspira",
    how_step2_title: "Compre normalmente",
    how_step2_desc: "Acesse as lojas parceiras e compre como sempre",
    how_step3_title: "Cashback vira doação",
    how_step3_desc: "O cashback é automaticamente doado para sua ONG",
    how_cta: "Ver lojas parceiras",
  },
  features: {
    feat_title: "Por que usar?",
    feat_subtitle: "Transforme seu consumo em impacto social",
    feat_1_title: "100% Gratuito",
    feat_1_desc: "Não paga nada a mais. O cashback vem da loja.",
    feat_2_title: "Transparência Total",
    feat_2_desc: "Acompanhe cada centavo doado em tempo real.",
    feat_3_title: "ONGs Verificadas",
    feat_3_desc: "Todas as ONGs são verificadas e auditadas.",
    feat_4_title: "Impacto Real",
    feat_4_desc: "Veja o impacto das suas doações.",
    feat_5_title: "Fácil de Usar",
    feat_5_desc: "Basta comprar nas lojas parceiras.",
    feat_6_title: "Seguro",
    feat_6_desc: "Seus dados são protegidos pela LGPD.",
  },
  stores: {
    stores_title: "Lojas Parceiras",
    stores_subtitle: "Compre e gere cashback solidário",
    stores_cta: "Ver todas as lojas",
  },
  ngos: {
    ngos_title: "ONGs Parceiras",
    ngos_subtitle: "Escolha para quem doar",
    ngos_cta: "Ver todas as ONGs",
  },
  stats: {
    stat_title: "Nosso Impacto",
    stat_subtitle: "Números que inspiram",
    stat_donated: "Doados",
    stat_users: "Usuários",
    stat_ngos: "ONGs apoiadas",
    stat_stores: "Lojas parceiras",
    stat_transactions: "Transações",
    stat_avg: "Ticket médio",
  },
  testimonials: {
    testimonial_title: "O que dizem",
    testimonial_subtitle: "Depoimentos de quem já usa",
    testimonial_1_name: "Ana Silva",
    testimonial_1_text: "Nunca imaginei que comprar online pudesse ajudar tanta gente!",
    testimonial_2_name: "Carlos Mendes",
    testimonial_2_text: "A transparência da plataforma é incrível. Sei exatamente para onde vai cada centavo.",
    testimonial_3_name: "Mariana Costa",
    testimonial_3_text: "Fácil de usar e com um propósito maravilhoso. Recomendo!",
  },
  faq: {
    faq_title: "Perguntas Frequentes",
    faq_subtitle: "Tire suas dúvidas",
    faq_q1: "É gratuito?",
    faq_a1: "Sim! Você não paga nada a mais. O cashback é gerado pela loja parceira.",
    faq_q2: "Como funciona o cashback?",
    faq_a2: "Ao comprar em uma loja parceira, parte do valor é devolvido como cashback e doado para a ONG que você escolheu.",
    faq_q3: "Posso escolher a ONG?",
    faq_a3: "Sim! Você escolhe a ONG que vai receber suas doações.",
    faq_q4: "Quanto tempo leva para confirmar?",
    faq_a4: "O cashback é confirmado pela loja em até 90 dias após a compra.",
    faq_q5: "Posso resgatar o cashback em dinheiro?",
    faq_a5: "Não. O cashback é 100% doado para a ONG escolhida. Essa é a essência da plataforma.",
  },
  cta: {
    cta_title: "Pronto para fazer a diferença?",
    cta_subtitle: "Comece agora mesmo. É grátis!",
    cta_button: "Criar conta grátis",
  },

  // ── Home logado ──
  home_logged: {
    home_greeting: "Olá, {name}! 👋",
    home_subtitle: "Continue fazendo a diferença",
    home_your_ngo: "Sua ONG",
    home_change_ngo: "Trocar",
    home_no_ngo: "Nenhuma ONG selecionada",
    home_select_ngo: "Escolher ONG",
    home_stores_title: "Lojas em destaque",
    home_see_all_stores: "Ver todas",
  },

  // ── Navegação ──
  nav: {
    nav_home: "Início",
    nav_stores: "Lojas",
    nav_ngos: "ONGs",
    nav_impact: "Impacto",
    nav_login: "Entrar",
    nav_signup: "Criar conta",
    nav_profile: "Perfil",
  },

  // ── Rodapé ──
  footer: {
    footer_copyright: "© 2026 MyCashbacks. Todos os direitos reservados.",
  },

  // ── Página de ONGs ──
  ngos_page: {
    title: "ONGs Parceiras",
    subtitle: "Escolha a ONG que vai receber suas doações",
    search_placeholder: "Buscar ONGs...",
    received_label: "recebidos",
    select_btn: "Selecionar",
    selected_label: "Sua escolha",
    empty: "Nenhuma ONG encontrada",
  },

  // ── Página de Lojas ──
  stores_page: {
    title: "Lojas Parceiras",
    subtitle: "Compre e gere cashback solidário",
    search_placeholder: "Buscar lojas...",
    cashback_label: "cashback",
    empty: "Nenhuma loja encontrada",
  },

  // ── Impacto ──
  impact: {
    title: "Seu Impacto 💜",
    subtitle: "Acompanhe suas doações",
    label_pending: "Pendente",
    label_confirmed: "Confirmado",
    label_donated: "Doado",
    transactions_title: "Transações",
    status_tracked: "Rastreado",
    status_pending: "Pendente",
    status_confirmed: "Confirmado",
    status_donated: "Doado",
    status_reverted: "Revertido",
  },

  // ── Transparência ──
  transparency: {
    title: "Transparência 📊",
    subtitle: "Dados abertos sobre todas as doações",
    total_label: "Total doado pela plataforma",
    ngos_label: "ONGs",
    donations_label: "doações",
    chart_title: "Distribuição por ONG",
    breakdown_title: "Detalhamento por ONG",
    recent_title: "Últimas doações",
  },

  // ── Login / Cadastro ──
  auth: {
    login_title: "Bem-vindo de volta!",
    login_subtitle: "Entre para continuar doando",
    signup_title: "Crie sua conta",
    signup_subtitle: "Comece a fazer a diferença hoje",
    forgot_title: "Esqueceu a senha?",
    forgot_subtitle: "Enviaremos um link para redefinir",
    google_btn: "Continuar com Google",
    or: "ou",
    name_placeholder: "Seu nome",
    password_placeholder: "Senha",
    forgot_link: "Esqueceu a senha?",
    login_btn: "Entrar",
    signup_btn: "Criar conta",
    no_account: "Não tem conta? ",
    has_account: "Já tem conta? ",
    signup_link: "Cadastre-se",
    login_link: "Entrar",
    back_to_login: "Voltar ao login",
    forgot_btn: "Enviar link",
    agree_prefix: "Concordo com os",
    terms_link: "Termos de Uso",
    agree_and: "e a",
    privacy_link: "Política de Privacidade",
    login_success: "Bem-vindo de volta!",
    agree_error: "Aceite os termos para continuar",
    signup_success: "Conta criada! Verifique seu email para confirmar o cadastro.",
    forgot_success: "Email de redefinição enviado! Verifique sua caixa de entrada.",
    google_error: "Erro ao entrar com Google",
  },

  // ── Perfil / Configurações ──
  settings: {
    title: "Meu Perfil",
    name_placeholder: "Seu nome",
    city_placeholder: "Sua cidade",
    save_btn: "Salvar",
    save_error: "Erro ao salvar perfil",
    save_success: "Perfil salvo",
    your_ngo: "Sua ONG",
    no_ngo: "Nenhuma ONG selecionada",
    choose_ngo: "Escolher ONG",
    change_ngo: "Trocar ONG",
    loading: "Carregando...",
    notifications_title: "Notificações",
    push_label: "Push (navegador)",
    push_desc: "Receba alertas no navegador",
    whatsapp_desc: "Receba atualizações no WhatsApp",
    email_desc: "Receba novidades por e-mail",
    appearance_title: "Aparência",
    theme_light: "Claro",
    theme_dark: "Escuro",
    theme_auto: "Auto",
    logout_btn: "Sair da conta",
    logout_msg: "Você saiu da sua conta",
    delete_account_link: "Excluir minha conta",
    delete_title: "Excluir conta",
    delete_warning: "Seus dados pessoais serão anonimizados conforme a LGPD. Registros de doações serão mantidos sem identificação pessoal. Esta ação não pode ser desfeita.",
    cancel: "Cancelar",
    confirm_delete: "Confirmar exclusão",
    delete_msg: "Conta excluída. Seus dados serão anonimizados conforme LGPD.",
    privacy_link: "Privacidade",
    terms_link: "Termos de Uso",
  },

  // ── Notificações ──
  notifications_page: {
    title: "Notificações",
    unread: "não lidas",
    empty: "Sem notificações",
  },

  // ── Privacidade ──
  privacy: {
    back: "Voltar",
    title: "Política de Privacidade",
    last_update: "Última atualização: Março de 2026",
    s1_title: "1. Coleta de Dados",
    s1_text: "Coletamos apenas os dados necessários para o funcionamento da plataforma: nome, email, e informações de navegação para rastreamento de cashback.",
    s2_title: "2. Uso dos Dados",
    s2_text: "Seus dados são utilizados exclusivamente para: identificação na plataforma, rastreamento de cashback, direcionamento de doações e comunicação sobre suas transações.",
    s3_title: "3. Compartilhamento",
    s3_text: "Não vendemos ou compartilhamos seus dados pessoais com terceiros, exceto com as lojas parceiras para fins de rastreamento de compras.",
    s4_title: "4. LGPD",
    s4_text: "Em conformidade com a Lei Geral de Proteção de Dados (LGPD), você tem direito a: acessar seus dados, corrigi-los, excluí-los e solicitar a portabilidade.",
    s5_title: "5. Exclusão de Conta",
    s5_text: "Ao solicitar exclusão, seus dados pessoais serão anonimizados. Registros de doações são mantidos para transparência, porém sem identificação pessoal.",
    s6_title: "6. Cookies",
    s6_text: "Utilizamos cookies essenciais para autenticação e cookies de rastreamento para contabilizar cashback corretamente.",
    s7_title: "7. Contato",
    s7_text: "Para dúvidas sobre privacidade, entre em contato: privacidade@mycashbacks.com.br",
  },

  // ── Termos ──
  terms: {
    back: "Voltar",
    title: "Termos de Uso",
    last_update: "Última atualização: Março de 2026",
    s1_title: "1. Aceitação",
    s1_text: "Ao utilizar a plataforma MyCashbacks, você concorda com estes termos de uso.",
    s2_title: "2. Funcionamento",
    s2_text: "O MyCashbacks intermedia a doação de cashback gerado por compras em lojas parceiras para ONGs cadastradas na plataforma. O cashback é 100% doado.",
    s3_title: "3. Cashback",
    s3_text: "As taxas de cashback são definidas pelas lojas parceiras e podem variar. O valor é confirmado após a loja validar a compra, o que pode levar até 90 dias.",
    s4_title: "4. Doações",
    s4_text: "O cashback confirmado é automaticamente doado para a ONG selecionada pelo usuário no momento da compra. Não é possível resgatar cashback em dinheiro.",
    s5_title: "5. Responsabilidades",
    s5_text: "O MyCashbacks não é responsável por problemas na compra junto à loja parceira. Questões de troca, devolução e garantia devem ser tratadas diretamente com a loja.",
    s6_title: "6. Cancelamento",
    s6_text: "Você pode excluir sua conta a qualquer momento. Cashbacks pendentes serão perdidos. Cashbacks já doados não podem ser revertidos.",
    s7_title: "7. Alterações",
    s7_text: "Reservamo-nos o direito de alterar estes termos. Notificaremos os usuários sobre mudanças significativas.",
  },

  // ── Onboarding ──
  onboarding: {
    title: "Bem-vindo ao MyCashbacks! 🎉",
    subtitle: "Configure seu perfil para começar",
    phone_label: "Seu telefone",
    ngo_label: "Escolha sua ONG",
    finish_btn: "Começar a doar!",
  },
};
